# Generated by Django 6.0.5 on 2026-05-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
