# Generated by Django 6.0.5 on 2026-05-20 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_alter_flight_arrival_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
