# Generated by Django 6.0.5 on 2026-05-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_booking_booking_date_booking_arrival_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
